controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

provincias_por_pais:
    path: /ajax/provincias
    controller: App\Controller\NegocioController::provinciasPorPais

localidades_por_provincia:
    path: /ajax/localidades
    controller: App\Controller\NegocioController::localidadesPorProvincia
